### ISSUE TITLE
Display bug on Subproject Page

### ISSUE THREAD

**Issue by loitq07** [yenihayat/redmine-theme-yh#1]
All looks perfect, except for the Subproject Page. Take a look at my attachment for details.
![issues - 143_claptofindphone - ros nation 2018-12-12 13-43-12](https://user-images.githubusercontent.com/8780784/49851554-09ae0280-fe14-11e8-93c7-0c1e589b11ad.png)

**Comment by cntrn** [comment]
Hi loitq07, what is your redmine version?

**Comment by loitq07** [comment]
Mine is Redmine 3.2.1 Stable. Can you help testing.
![image](https://user-images.githubusercontent.com/8780784/49907767-4298b680-feaa-11e8-9008-b26691b884c6.png)

**Comment by cntrn** [comment]
fixed in release 1.2
