### ISSUE TITLE
Projects page list broken

### ISSUE THREAD

**Issue by jboilesen** [yenihayat/redmine-theme-yh#18]
The projects page list is broken.

![projects_broken](https://user-images.githubusercontent.com/4542170/51690429-ce404f80-1fdf-11e9-9a39-094d9648037e.png)

**Comment by cntrn** [comment]
page looks alright on redmine v3.4.8 at chrome.
try hard refresh your browser

**Comment by jboilesen** [comment]
Version 3.4.6.stable here, chrome too

Did a hard reset but it didn't work.

Projects break when the window width is bigger than 1024px

**Comment by cntrn** [comment]
tested at 3.4.6 stable, no problems.
can you try it in another browser
