### ISSUE TITLE
Missing quick-search on PC device

### ISSUE THREAD

**Issue by pasqualedante** [yenihayat/redmine-theme-yh#19]
There isn't quick-search field near jump-to-project.
Running termine 3.4

**Comment by pasqualedante** [comment]
![screenshot_2019-02-26-19-05-23-191_org mozilla firefox_beta](https://user-images.githubusercontent.com/813690/53435936-41335080-39fa-11e9-9379-4f192d6733b8.png)

**Comment by cntrn** [comment]
quick-search is inside the jump-the-project dropdown.

**Comment by pasqualedante** [comment]
> quick-search is inside the jump-the-project dropdown.

I refer to quick-search that is near the Jump-To-Project and not into and that is used to search for text, ids etc.
This on another theme
<img width="318" alt="other-theme" src="https://user-images.githubusercontent.com/813690/53556357-eefe4680-3b43-11e9-8eef-196e58220541.png">

This on redmine-theme-yh on mobile device
<img width="272" alt="mobile" src="https://user-images.githubusercontent.com/813690/53556380-00dfe980-3b44-11e9-88f5-58d671da11ad.png">


Thanks for all your good work.

**Comment by tkitynski** [comment]
Pasqualdente's right—it's not about filtering projects, but performing search on whole DB. It's where you normally type e.g. #45 looking for an issue with id 45, but not only this. Currently typing #<id> into quick search gives no results (of course <id> issue is available). I like yours skin style the best, thou. Can we count on fixing that search input?

**Comment by cntrn** [comment]
fixed

**Comment by tkitynski** [comment]
Great! It works! Thank you! 8)

**Comment by cntrn** [comment]
you're welcome :)
