### ISSUE TITLE
(Mobile) Custom widget table in My Page, overflow over lateral menu

### ISSUE THREAD

**Issue by pasqualedante** [yenihayat/redmine-theme-yh#20]
As stated in subject, see attached screenshot

**Comment by pasqualedante** [comment]
![img_20190305_211241](https://user-images.githubusercontent.com/813690/53834684-fc746000-3f8b-11e9-9fd3-11e55ba00d96.jpg)

**Comment by pasqualedante** [comment]
![53834684-fc746000-3f8b-11e9-9fd3-11e55ba00d96](https://user-images.githubusercontent.com/813690/53863271-0f1d8200-3fea-11e9-8810-ac32e641dba7.jpg)

**Comment by cntrn** [comment]
fixed
