### ISSUE TITLE
Missing icons and unstyled buttons

### ISSUE THREAD

**Issue by jboilesen** [yenihayat/redmine-theme-yh#8]
Some pages are missing buttons icons and/or styling:

**1. Go to page /users/1/edit**
The icons to "profile" and "emails" are unstyled
![user_edit](https://user-images.githubusercontent.com/4542170/51611185-c7dda500-1f05-11e9-9973-ff36f0ef7687.png)

**2. Go to page /users/1/edit and click on button "Emails"**

The add emails dialog is unstyled
![user_edit_email](https://user-images.githubusercontent.com/4542170/51611222-ddeb6580-1f05-11e9-9153-a97f6de9ecbe.png)

**3. Go to a project and add a new issue (/issues/new)**
The "search for others observers" button is unstyled and it's dialog is unstyled too.

The button:
![new_issue](https://user-images.githubusercontent.com/4542170/51611549-a03b0c80-1f06-11e9-910d-be91b8738819.png)

The dialog:
![new_issue_observer_dialog](https://user-images.githubusercontent.com/4542170/51611625-d2e50500-1f06-11e9-927f-1a65f4b7c3ac.png)

**4. Closed/Archived Project icon and Open/Unarchive Project icon**
Archive a project and you will get this:
![archived_project](https://user-images.githubusercontent.com/4542170/51611745-26575300-1f07-11e9-917f-00eee71cd61e.png)

Finally, really nice theme!!! Nice work and thanks for sharing. :+1:

**Comment by cntrn** [comment]
fixed
